name: Docker Image CI

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jfmartineb/computienda:latest
      
    - name: Docker Push
      run: docker push jfmartineb/computienda

